server:
  port: 8088
spring:
  application:
    name: demo
  datasource:
    url: jdbc:mysql://localhost:3306/tayjava
    username: root
    password:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update